[canvas]
width = 384
height = 192

[margins]
left_margin = 8
right_margin = 8
top_margin = 26
bottom_margin = 10

[background]
bg_image_is_set = true
background_image = "bg_images/calculator.png"

[showing_screen]
show_screen = true
close_window = true

[saving_screen]
save_screen = false
image_name = "casioplot"
image_format = "png"
save_multiple = false
save_rate = 1
